server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: 8.131.86.156:8848/ #配置Nacos地址
        # 换成nginx的1111端口，做集群
        server-addr: 8.131.86.156:1111

management:
  endpoints:
    web:
      exposure:
        include: '*'