server:
  port: 9527

spring:
  application:
    name: gateWay-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由功能，利用微服务名进行路由
      routes:
        # - id可以配置多个
        - id: payment_routh1 #路由的ID，没有固定规则，但要求唯一，建议配合服务名
          # uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          # filters:
            #过滤器工厂会在匹配的请求头上加一对请求头，名称为X-Request-Id，值为1024
            # - AddRequestParameter=X-Request-Id,1024
          predicates:
            - Path=/payment/getOne/** #断言，路径相匹配的进行路由
            # - After=2020-11-04T23:07:42.153+08:00[Asia/Shanghai]
            # - Cookie=username,yyb
            # - Header=X-Request-Id,\d+ #请求头要有X-Request-Id属性并且值为整数的才能匹配
            # - Host=**.itan.com
            # - Method=POST
            # - Query=username, \d+ #要有参数名称username，并且是正整数才能路由

        - id: payment_routh2 #路由的ID，没有固定规则，但要求唯一，建议配合服务名
          # uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/timeout/** #断言，路径相匹配的进行路由

eureka:
  # 设置服务名称信息（自定义）并设置访问路径可以显示 IP 地址
  instance:
    instance-id: gateWay9527
    prefer-ip-address: true
  client:
    # 表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    # 客户端注册进 eureka 服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka