server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 8.131.86.156:8848/ #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'