server:
  port: 80

eureka:
  # 设置服务名称信息（自定义）并设置访问路径可以显示 IP 地址
  instance:
    instance-id: hystrix80
    prefer-ip-address: true
  client:
    # 表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: false
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    # 客户端注册进 eureka 服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与服务生产端不一样。